//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI_DesktopApp.EDIServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/EDITranslatorServiceLib")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rev-a-shelf.com", ConfigurationName="EDIServiceRef.ITranslator")]
    public interface ITranslator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rev-a-shelf.com/ITranslator/GetEDIDocFromJSON", ReplyAction="http://rev-a-shelf.com/ITranslator/GetEDIDocFromJSONResponse")]
        string GetEDIDocFromJSON(string jsonSegment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rev-a-shelf.com/ITranslator/GetEDIDocFromJSON", ReplyAction="http://rev-a-shelf.com/ITranslator/GetEDIDocFromJSONResponse")]
        System.Threading.Tasks.Task<string> GetEDIDocFromJSONAsync(string jsonSegment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rev-a-shelf.com/ITranslator/GetEDIDocFromXML", ReplyAction="http://rev-a-shelf.com/ITranslator/GetEDIDocFromXMLResponse")]
        string GetEDIDocFromXML(string xmlSegment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rev-a-shelf.com/ITranslator/GetEDIDocFromXML", ReplyAction="http://rev-a-shelf.com/ITranslator/GetEDIDocFromXMLResponse")]
        System.Threading.Tasks.Task<string> GetEDIDocFromXMLAsync(string xmlSegment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rev-a-shelf.com/ITranslator/GetJSONFromEDIDoc", ReplyAction="http://rev-a-shelf.com/ITranslator/GetJSONFromEDIDocResponse")]
        string GetJSONFromEDIDoc(string ediDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rev-a-shelf.com/ITranslator/GetJSONFromEDIDoc", ReplyAction="http://rev-a-shelf.com/ITranslator/GetJSONFromEDIDocResponse")]
        System.Threading.Tasks.Task<string> GetJSONFromEDIDocAsync(string ediDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rev-a-shelf.com/ITranslator/GetXMLFromEDIDoc", ReplyAction="http://rev-a-shelf.com/ITranslator/GetXMLFromEDIDocResponse")]
        string GetXMLFromEDIDoc(string ediDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rev-a-shelf.com/ITranslator/GetXMLFromEDIDoc", ReplyAction="http://rev-a-shelf.com/ITranslator/GetXMLFromEDIDocResponse")]
        System.Threading.Tasks.Task<string> GetXMLFromEDIDocAsync(string ediDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rev-a-shelf.com/ITranslator/GetDataUsingDataContract", ReplyAction="http://rev-a-shelf.com/ITranslator/GetDataUsingDataContractResponse")]
        EDI_DesktopApp.EDIServiceRef.CompositeType GetDataUsingDataContract(EDI_DesktopApp.EDIServiceRef.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rev-a-shelf.com/ITranslator/GetDataUsingDataContract", ReplyAction="http://rev-a-shelf.com/ITranslator/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<EDI_DesktopApp.EDIServiceRef.CompositeType> GetDataUsingDataContractAsync(EDI_DesktopApp.EDIServiceRef.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITranslatorChannel : EDI_DesktopApp.EDIServiceRef.ITranslator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TranslatorClient : System.ServiceModel.ClientBase<EDI_DesktopApp.EDIServiceRef.ITranslator>, EDI_DesktopApp.EDIServiceRef.ITranslator {
        
        public TranslatorClient() {
        }
        
        public TranslatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TranslatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetEDIDocFromJSON(string jsonSegment) {
            return base.Channel.GetEDIDocFromJSON(jsonSegment);
        }
        
        public System.Threading.Tasks.Task<string> GetEDIDocFromJSONAsync(string jsonSegment) {
            return base.Channel.GetEDIDocFromJSONAsync(jsonSegment);
        }
        
        public string GetEDIDocFromXML(string xmlSegment) {
            return base.Channel.GetEDIDocFromXML(xmlSegment);
        }
        
        public System.Threading.Tasks.Task<string> GetEDIDocFromXMLAsync(string xmlSegment) {
            return base.Channel.GetEDIDocFromXMLAsync(xmlSegment);
        }
        
        public string GetJSONFromEDIDoc(string ediDoc) {
            return base.Channel.GetJSONFromEDIDoc(ediDoc);
        }
        
        public System.Threading.Tasks.Task<string> GetJSONFromEDIDocAsync(string ediDoc) {
            return base.Channel.GetJSONFromEDIDocAsync(ediDoc);
        }
        
        public string GetXMLFromEDIDoc(string ediDoc) {
            return base.Channel.GetXMLFromEDIDoc(ediDoc);
        }
        
        public System.Threading.Tasks.Task<string> GetXMLFromEDIDocAsync(string ediDoc) {
            return base.Channel.GetXMLFromEDIDocAsync(ediDoc);
        }
        
        public EDI_DesktopApp.EDIServiceRef.CompositeType GetDataUsingDataContract(EDI_DesktopApp.EDIServiceRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<EDI_DesktopApp.EDIServiceRef.CompositeType> GetDataUsingDataContractAsync(EDI_DesktopApp.EDIServiceRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
